sudo: false
language: python
python:
  - "3.5"
  - "3.6"
branches:
  only:
    - master
# command to install dependencies

before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.19.0/geckodriver-v0.19.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.19.0-linux64.tar.gz -C geckodriver
  - chmod +x geckodriver/geckodriver
  - export PATH=$PATH:$PWD/geckodriver

install:
  - pip install -r requirements.txt
  - pip install -U codecov

# command to run tests
script:
  # Not sure if this is the right one. So, if someone sees this, can you please correct me? Thanks :)
  - coverage run manage.py test

after_success:
  - codecov
