sudo: false
language: python
python:
  - "3.5"
  - "3.6"
branches:
  only:
    - master
# command to install dependencies

install:
  - pip install -r requirements.txt
  - pip install -U codecov
# command to run tests
script:
  - coverage run manage.py test

after_success:
  - codecov
