sudo: false
language: python
python:
  - "3.5"
  - "3.6"
branches:
  only:
    - master
# command to install dependencies

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_install:

install:
  - pip install -r requirements.txt
  - pip install -U codecov

# command to run tests
script:
  # Not sure if this is the right one. So, if someone sees this, can you please correct me? Thanks :)
  - coverage run manage.py test

after_success:
  - codecov
